ekf:
  ros__parameters:
    relative_mode: true
    imu_dt: 0.01 # TODO rewrite to also use timestamp dt when this value is 0.0
    imu_step_delay: 10 # 125

    # Q
    # process noise std
    process_noise_roll: 0.005
    process_noise_pitch: 0.005
    process_noise_yaw: 0.005

    # R
    # measurement noise std
    # measurement_noise_ori: 0.00001
    measurement_noise_roll:  0.01
    measurement_noise_pitch: 0.01
    measurement_noise_yaw:   0.01

    # Q
    process_noise_pos: 0.05 # 0.01> x >0.0007 
    # process_noise_x: 0.001
    # process_noise_y: 0.001
    # process_noise_z: 0.001

    # R
    measurement_noise_pos: 0.005 # is manually updated from LO estimation
    measurement_noise_imu: 0.01
    # measurement_noise_x: 0.00001
    # measurement_noise_y: 0.00001
    # measurement_noise_z: 0.00001

    init_calib_steps: 0 # if zero no initial calib is done
    imu_topic: "/imu/data"
    # imu_topic: "/imu/data"

    print_states: true
    use_madgwick_orientation: true
