lidar_odometry:
  ros__parameters:
    ds_voxel_size: 0.2
    ds_voxel_size_lc: 0.1
    use_cloud_scale_for_ds: true # if this is false above are used, if true below are used
    cloud_scale_previuos_cloud_weight: 0.9 # 0-1
    ds_lc_voxel_size_ratio: 50.0 # the bigger, the finer the local map is
    points_per_cloud_scale: 25
    # parameters for when to keyframe
    keyframe_threshold_length: 0.1 # meters
    keyframe_threshold_angle: 2.0 # deg
    keyframe_threshold_fitness: 0.1
    keyframe_threshold_index: 0
    icp_max_iterations: 50
    icp_max_correspondance_distance: 0.2
    local_map_width: 40
    local_map_init_frames_count_: 0
    use_fusion_with_imu: false

