lidar_odometry:
  ros__parameters:
    ds_voxel_size: 0.05 # <0.05
    ds_voxel_size_lc: 0.01 # 0.01
    use_cloud_scale_for_ds: false # if this is false above are used, if true below are used
    cloud_scale_previuos_cloud_weight: 0.9 # 0-1
    ds_lc_voxel_size_ratio: 200.0 # the bigger, the finer the local map is
    points_per_cloud_scale: 10
    keyframe_threshold_length: 0.01 # meters, 2.0 is good, 0.02 for dense maps!
    keyframe_threshold_angle: 35.0 # deg, 30 is good
    keyframe_threshold_fitness: 0.5
    keyframe_threshold_index: 0 # 0 means it is not used
    scan_matching_method: 0 # 0 ICP-p2pl, 1 GICP, 2 NDT-p2d
    icp_max_iterations: 5 # 10-30
    icp_max_coarse_iterations: 2 # 10-30
    icp_max_correspondence_distance: 0.001 # should be less than voxelsize of source
    coarse_correspondence_factor: 100
    local_map_width: 20 # if 0 all previous keyframes are pushed to local map indefinitely
    local_map_init_frames_count: 20
    # use_inertial_constraint: false
    # use_wheel_constraint: false
    use_ins_guess: false
    use_preint_imu_guess: false
    imu_topic: "/imu/data"

    use_linear_undistortion: true


    translation_std_min_x: 0.01
    translation_std_min_y: 0.01
    translation_std_min_z: 0.01

    # use_fusion_with_imu: false # i this needed here?

