preprocessing:
  ros__parameters:
    lidar_source_topic: "/livox"
    # lidar_source_topic: "/velodyne"
    pre_downsample_leaf_size: 0.0 # if 0.0  the cloud is not downsampled
    filter_close_points_distance_m: 1.0 # in meters
    filter_max_intensity: 175.0 # the maximum value is 255
    use_gyroscopic_undistortion: false
    # if both of the following are 0 no normals will be calculated
    
    pc_normal_search_radius: 0.0 # this is currently not used as it is not robust to variation in the cloud size which is apparent for pc from the livox lidar. large scale is 2.0, small scale is 0.2
    pc_normal_knn_points: 25 # This is currently used over search_radius, 30
    
    edge_threshold: 0.5
    surfaces_threshold: 0.01
    remove_statistical_outliers_knn_points: 25
    remove_statistical_outliers_std_mul: 2.5 # 1.5

    remove_transition_outliers_cos_angle_threshold: 0.9996 #0.996195 # cos(5 degrees) = 0.996195

    normalize_intensities_reference_range: 1.0 # if this is zero the processing of this is off
    calculate_point_curvature_kernel_width: 0 # 1
    calculate_point_plateau_kernel_width: 0 # 2


    start_idx: 0 # skip x first frames
    end_idx: 0

    # if any value is 0 or 0.0 the element is disabled